language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: Uj0Kaphb9Cs+bq69bqg/mEIAJUoMCwl/ZVPLm9eplCYPngwUwOPfy/0zUPLyai6c/ycFQuuBjyR4eP0JLuviciwAX/e1mf4fQweNURnVn2wPoSBmHkSS08zbmE+C4AWyG3EU2/qyhrkSuuUOMFnWUXp7BLy78hijCe7ij88TdQg=
  - secure: diiPWBySv2y8mVpgHHl1dDIshlxNTG0ygF/q8sbfvIa2M7K5y/jiG5+nmqXOruOfYLcSmRJ49Eu+p6mFEZGzfWc/uGuL/yNzJiHBdZYLZ7ijEV7Tt3Kj0wDrrV498cqVin+/mPoJAtLmldVqCUpImxn74g0VYXBMwPibIeiQFfQ=
notifications:
  email: false
before_script: npm install -g karma-cli
