language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
    - secure: Rtk7KIR6DMAQxMxj7EXkaIfdpK9z0FRvEXpuRk60k0DG4AbnIbGB9Pru0Jkl5MnvOJ7fE9vKlQ8GN58OQdkl/SBmGsYsTXksy1Ms4rncTdRwgdlHR/RXMtpOiAr3iNPrUjPA4XJKwOWCCX32o3ZfSO4+osbeMX5gbmK+tmq/DOY=
    - secure: ViBynDqX9IBAYh4kCTPv4crFfr2MRbDG7oyrUrh7KcYD2QzVFxhuPubgRTeEpfwTATXPE4ykDti6annQUp85WL3fKj2/MwQWx8YgBsyzWRZVYibZ6lrYamuyzsv4b/PoAHZvhiCsEppMT3MctcfnJ436hkcgblG/TOKMUVWQ3dM=
notifications:
  email: false
before_script: npm install -g karma-cli
