language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: cMNXDOQUjk405p4DRep9DQqUneANtd6S6PZ7EeVfRSQOMaJ0xGL40NC0n+bYSXcIhSZH9jPVqi92nFzpQroZV+ydAGYIr5maCXDzwiVHiOakSLjTtUE/SICNo2f0inPidhg0QGfL1Beav/Qq/BEN4u9VJw5aU07vqGSJpSImkTI=
  - secure: PQhS+uLhprWszmR+bk6fOlO3fjv2sxCgu16gPXwpZn9u2G1xpi1wQwK1qSPFsFigSGQ/KDmhFS1Oy4Tk1RyniOYy9OwLokR475H9cxVY2/0PgE+zWgIM4uQDO52FKB+yuazoCI7Xz8xSOMU3wXar9sjUN1VboDcEmBymRw5desU=
notifications:
  email: false
before_script: npm install -g karma-cli
