language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: gxjuUv+B/qgKcGLxLYHjrH4o8ccvf4e9XwUqC4d/+dpSs1creRoBa9qUUkzTRtcx8O2gKc2ziLh0m/hz16Jfz99IPlO0O/toDkKzH5tno/fO6hZLs4WhQE4WdyP7LffhLui28vpzFYCLIizbWC7WRe6ToQ6hbbW7cGGlnitVZ78=
  - secure: NFTQ2w0AyrqjYK0Ck/OoNZyhXyxMcSVABFebE/wfW8VqHgE1rTdb+G6dBQXcvBwInsRK2C180/8kNAqpYyVULbEH+tT85yTle/1ykvqpQ+RMXhvTFv4l0rxFJy2u9JpWXjch+U7pe2e7MmiTAza02/nuwzxZ52jvEKiVeex5duQ=
notifications:
  email: false
before_script: npm install -g karma-cli
