language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: q5C4Bl8VsL+cN0hMuEqt5+Ki+fZt17oQCXidOMg9GY9iYWGTYqUIYhetMfvBnStL+gxCeUM0JhXFQPF1dRUCReTCcJhBwwHp6BRl8uSleoXmnPpVCNNQKMmX/QcZTih6fxiE3IVDfuJ6VQIb2zGIngfem+kOi9dcO3ECHUSf0Vo=
  - secure: lBC5zm/tuNbZPPe4uCYdVdWoZFAyRKnWHd7WfE/gZLV/vcwFqWM9yz8RbcRMe1DKQygRvyI9WEnieh3zfjjtAYR4T2WnWj3K8OHNn9Erktd0RS6M/eJqWbJOmu8VTp6cYIfv4dGMkFVzZ1eiozkepjGMfqhu+kZDXJ/dgdaUSms=
notifications:
  email: false
before_script: npm install -g karma-cli
