language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: Hn6tyyc28rFvq+GCj6uhIYmpWr30q8rpKxoVFB8xW7NHM4PCfce1Czsvaq0aKhCYmI7usmVNM3B1m3scr8LdZMdoM2HCXUwCh23Ar/VQNHSA3PST6dxtgVEysY+M0QO30AcjWDZCGIftQGxG60U+xpBjCkWGUfOr86er2g1VICI=
  - secure: aF2gsOGbEL88YCr+Ejq6w7Kay+Fok/Fsm7CjvMfRfM9KPHKqTHu8OTTK/W7DMj72RB/atl/kiZMLgec8HDrJ/5TEeOPkvCFlGHfnjur4rbxtUrxkTe/ld9i+0cDzcjB5jXKcYAB3YOl5yGNAlbl3mSZPJtH5XJ2JKogag+0q4WY=
notifications:
  email: false
before_script: npm install -g karma-cli
