language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: EMNVGDG4ij1NREMkGS28iMMKeg0PJcd/qGXDQ1HhUqWRlJWVLBF2YBLLqRFB833Q7L1mqDFx3bZll5DuwTg/+krOcOx5hWqY6tFRcW0zlgQiEsJZ8eoDZHQ6rZT2PjIWX0DYMU5CLnoi4YdfqfrLEPcIsiIEasYDdLGtKDXP2mA=
  - secure: fR/3sResYamKYdWbXiLMpOUJLBWp38S9r4H18wF97TuMDa9oy448sQOHmXuGkk7chV0X6GSyNRIOmHpFRqfr2Oq5aKLNRoiJJBGRlTW7KqGMvvThOcGPByUMxROrZ4OND+/R8cl0PjocA2Y2YAnBHHyzJC9S8IOpfeljZ1C/92Q=
notifications:
  email: false
before_script: npm install -g karma-cli
