language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: OSA3wQ/g8s5b1ST8iRIjyOVqe4hQX1P8LN+HCN4tei9MRD0WrXlImayN/O1FcoT1NjJxsDYvkSF5QZokrJaidQSRg9r+LIxDKr+uLmNYK1zAPXZjPhMvE+az58dfoe1JVtrFwgiAshynGrJrk+ofDyHbiQrGt6xGMkCdZtIP98o=
  - secure: Bz+8mTk7GNCdlkb1X4WTsT9efYlB1NgnOj2LF6rk/4wZU0Wt3lFFq2m+uoNexcXugBHP8hzr2q+w4rHJe/0yCrJ3A6TdTcvSZGMBF01WP25vmR2hJ0Jh7boiAPV0xsPtK4opBf9JQW6tFwHPqHeObNej/VdytaQGPaydQ+57bDk=
notifications:
  email: false
before_script: npm install -g karma-cli
