language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
    - secure: dR7a5hKwvR+70+dCU0IZwb4/wDV8KvLGBIxwAWNJe1aSrlETFG+VxIxHfEUbBU2eNOyFlOYBb1n5MXfs4bCAlo1/nih+FJAzyJ0vqXt9GPKuzmlf86MYG6bk9x7ZAM6puP6O5e/oXgLw5wAUuGr1E87h08rNQpBAzS6JTJGm8gY=
    - secure: dWZYWJne6pkuK4Ul3Y6JVUe4h33RCrtfNc5Of9Fp2Wes8oaKH1PoV0/eVMKvT5WlNaC/x/mSPdggLyCs1MWiYUhitgqJOocwCGFzxHARbgea+7cA5VlFI6WkK1yJ92qnd9F0A/rBDFZYFkztpAe7FVAEofo6A+cwtXGzuEwrpIE=
notifications:
  email: false
before_script: npm install -g karma-cli
