language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: DFK5o4fIEMt6RkRNEEhQqxrbtEZvlRl2NWwNnfnyO+TzfsdMlRV2wKJaQKDFtGvt5XnXnSdl/bT1/AiUYeYftQ==
  - secure: JRRlibkwdJO6C7rijSGb3ECZxiadzLTibL+SmW0eT03KI8gNc736Y/RuiF0b4X3jE5I9bZVrrX28mBSe8wPZqQ==
notifications:
  email: false
before_script: npm install -g karma-cli
