language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: B+pAIERx7Nph4DX6Le1TEIdUhIbZ4fcoIdayUiSVK6IIeJaux7liu9Xa+ilxzKklREoMqS26TMYKgqBdPH0Od97yZDzgZgRDY0D/Fk76GMj68NkmUtpiiJG04tU7D8t/D873KeNPpq4BN8EEMQN7wq/p+le9ESJWHinbEr/PHZQ=
  - secure: pCmlROXeHCsDaAVs5v6dMVKmvPVAcjaF71y1+RtDy2Wg/oPPLdrvdZFzCQ+fZAIaDxtD/1esLG3bvSmIyhyw9rVQtnuTjM65Y+xf9nMrO5oCkDvU78SCDnQ44WeqSVEi8qocQfOmUQuVQ5Ha3uPf98UvL7O72zyWAEZd5eKetxg=
notifications:
  email: false
before_script: npm install -g karma-cli
