language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: bsxqEuOHT8HjhJsAspS1VpA582/F5Ii7QqlXwC+/8xnlKsF2ea2bizMHG29adWTqAxS3+DPrH1tqPlZGX7vWO2AUCnz138U/gZ1oR2XdabWVR2+mlxkcVpIpdZZjDOzJiuj8zWkGerPqoED8bo0BRNG4rxYv/6W6pycqWiy1BAs=
  - secure: gDNNlPFLQe4Ci6/Jxe3so7YENee1gr4Zo5ZOpitHvUb2Og/KUvFI0oY1OT7xDOriqBUo3x1UKHy+U1D/5Ogid18itjSdAO7mqIraIj3q5J0PcZbuDS5iGoxGGIrqzrxvFSUl0tIlfK/RQetE+iGPUycKK+q+4hHDCP7yiJV0MF0=
notifications:
  email: false
before_script: npm install -g karma-cli
