language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
    - secure: e/PDbO/XgGgo2UsUz5Tsdk+91IKgcJTU8C0LUfU2/hkWr2Fkv0A04VCoourJNE6BBtf1J8bVFyRjJzkT7NdS41y+34lIXLsOlNCZkQklAXIO+PbMThuN1XUSRMN6ZIjkeU+dEtdilJRb7Isc6XFWuB90YgVrKtlOd4zOisB47EU=
    - secure: F+RokosPdViTGv2XlJ5LTcJ0l4UMpyLhjPmzDPMQxN2J+R3g6X0irCJ5O7kVaCCI7Ff+nI6eB90w4RkUWSM1YccHMsrCmB+YDkrlNikWVom4ZYRfIfR87BkL61gGHZuDSyoWyF8kGWJxhFWtmObHR1Fm0Bl+fkaQAF0BEQbKgpA=
notifications:
  email: false
before_script: npm install -g karma-cli
