language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: RLn3qHXIMrxs67cRJTq7SmUcUzYrdvXxJZaD9c5KlOX+Xurc0XShvGrHlWd3y8qteSomx3uXBy4Qv2pZs33XFdwHa/SMYNOlFVzGBTCJEtWSTP3vXKD0yCivNaHwu/euG7Loyh6YTTwg7d+pK+ZWeaFkLjzHq4ft21EYrhg1lhA=
  - secure: by9HRUImhlvKF72cnsOXlgeH4Jku0wdUFGdOLGmVNPaaKeZCbQvOV0QhNLnQ/p2u7N3eqaBM0jEMx04NpJehENyJv1dm1ENyMlb5cA2EGaGQRue0TS+jGef3haAGfJLTmclr23yVB5WBJFQ78EsV9rM+Vqgi6sRTmhezte4KpDI=
notifications:
  email: false
before_script: npm install -g karma-cli
