language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - secure: 3153be13ca91e847668fbf430757a0b5
  - secure: 602730b8f5da7e14f87671935251ea17
notifications:
  email: false
before_script: npm install -g karma-cli
